# Generated by Django 6.0 on 2026-01-26 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('prenom', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('poste_nom', models.CharField(max_length=80)),
                ('nom_utilisateur', models.SlugField(editable=False, max_length=80, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_utilisateurs/')),
                ('est_actif', models.BooleanField(default=True)),
                ('est_staff', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avenue', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=20)),
                ('quartier', models.CharField(max_length=120)),
                ('commune', models.CharField(max_length=120)),
                ('niveau', models.CharField(max_length=50)),
                ('code_appartement', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('avenue', 'numero', 'quartier', 'commune', 'niveau', 'code_appartement'), name='unicite_adresse_exacte')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_comme_demandeur', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_comme_proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='fichiers_messages/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='immobilier.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos_publications/')),
                ('titre', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('prix', models.PositiveIntegerField()),
                ('statut_transaction', models.CharField(choices=[('A_LOUER', 'À louer'), ('A_VENDRE', 'À vendre')], max_length=20)),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('adresse', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='immobilier.adresse')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='immobilier.publication'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('proprietaire', models.F('demandeur')), _negated=True), name='conversation_proprietaire_different_demandeur'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('publication', 'demandeur'), name='unicite_conversation_par_publication_et_demandeur'),
        ),
    ]
