# Generated by Django 6.0 on 2026-01-26 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='immobilier.publication')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
