# Generated by Django 6.0 on 2026-01-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_signalement'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='est_lu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('TEXTE', 'Texte'), ('FICHIER', 'Fichier'), ('VOCAL', 'Vocal')], default='TEXTE', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='vocal',
            field=models.FileField(blank=True, null=True, upload_to='vocaux_messages/'),
        ),
    ]
